import Body from "./Body/Body"
import StoreProvider from "./StoreProvider"
import './Body/body.css'
import Accueil from "./page"


export const metadata = {
  title: 'One Crew',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <StoreProvider>
        <Body>
          {children}
        </Body>
      </StoreProvider>
    </html>
  )
}
